# Generated by Django 5.0.6 on 2024-12-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_account_log_token_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_log',
            name='token_id',
            field=models.CharField(default='0458664', max_length=255),
        ),
        migrations.AlterField(
            model_name='account_log',
            name='transactionId',
            field=models.CharField(default='lXKpvQlqq4', max_length=255),
        ),
        migrations.AlterField(
            model_name='chart_of_account',
            name='token_id',
            field=models.CharField(default='jnxvsLttQf', max_length=255),
        ),
        migrations.AlterField(
            model_name='transfer_account',
            name='token_id',
            field=models.CharField(blank=True, default='9fXrL5jR3x', max_length=12),
        ),
    ]
