# Generated by Django 5.0.6 on 2025-01-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_alter_account_log_token_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_log',
            name='token_id',
            field=models.CharField(default='9292929', max_length=255),
        ),
        migrations.AlterField(
            model_name='account_log',
            name='transactionId',
            field=models.CharField(default='fQIT7dZPTD', max_length=255),
        ),
        migrations.AlterField(
            model_name='chart_of_account',
            name='token_id',
            field=models.CharField(default='myf6UCGW1P', max_length=255),
        ),
        migrations.AlterField(
            model_name='transfer_account',
            name='token_id',
            field=models.CharField(blank=True, default='qnTxtPOWic', max_length=12),
        ),
    ]
