"""
Django settings for Afrikbook_proj project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

from django.conf.global_settings import AUTHENTICATION_BACKENDS

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import os
from dotenv import load_dotenv

load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bdad%tpby&zszmtofy=7ye6o2@98!=9#lq4tqy)$h&gz+x#&$-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG')

#EMAIL_HOST = 'smtp.gmail.com'
#EMAIL_HOST_USER = 'isdoremartins23@gmail.com'
#EMAIL_HOST_PASSWORD = 'etwkejogsyfimzbi'

EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
# EMAIL_PORT = 587
EMAIL_PORT = 465
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True # CHANGE EMAIL_USE_TLS = False

EMAIL_BACKEND= 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_BACKEND= 'django.core.mail.backends.console.EmailBackend'

PAYSTACK_SECRET_KEY = os.getenv('PAYSTACK_SECRET_KEY')

ALLOWED_HOSTS = ['69.10.53.253', 'console.afrikbook.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    # 'django.contrib.reportlab',
    'main.apps.MainConfig',

    # my apps
    #'main',
    'customer',
    'settings',
    'employee',
    'journal',
    'report',
    'filter',
    'vendor',
    'account',
    'widget',
    'Stock',
    'Stockin',
    'basic_sales_app',
    'client',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Afrikbook_proj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR, 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Afrikbook_proj.wsgi.application'


# Cache Configuration - ADD THIS
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'SOCKET_CONNECT_TIMEOUT': 5,
            'SOCKET_TIMEOUT': 5,
            'CONNECTION_POOL_KWARGS': {
                'max_connections': 50,
                'retry_on_timeout': True,
            },
        },
        'KEY_PREFIX': 'afrikbook',
        'TIMEOUT': 86400,  # 24 hours
    }
}

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgres',
#         'NAME': BASE_DIR / 'db.postgres',
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'afrik_database',
#         'USER': 'root',
#         'HOST': '127.0.0.1',
#         'PASSWORD': '',
#         'PORT': '3306' ,
#     },
    
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'afrikbook_db',
        'USER': os.getenv('DATABASE_USER'),
        'PASSWORD': os.getenv('DATABASE_PASSWORD'),
        'HOST': os.getenv('DATABASE_HOST'),
        'PORT': '5432',
    },
    
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [BASE_DIR / "static/"] 

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"

STATIC_ROOT = BASE_DIR /'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# lily settings configuration
MY_EXPERIMENT = True




# bright settings configurations

AUTH_USER_MODEL = 'main.User'

AUTHENTICATION_BACKENDS = {
    "main.backends.EmailAuthenticationBackend",
    "django.contrib.auth.backends.ModelBackend"
}







DATABASES['afrikbook_client'] = {
  'ENGINE': 'django.db.backends.postgresql',
  'NAME': 'afrikbook_client', 
  'USER': os.getenv('DATABASE_USER'),
  'PASSWORD': os.getenv('DATABASE_PASSWORD'),
  'HOST': os.getenv('DATABASE_HOST'),
  'PORT': '5432',
}
MY_URL = 'https://console.afrikbook.com'
API_TIMEOUT = 10
