# Generated by Django 5.0.6 on 2024-12-09 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_sales_order_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_addr',
            name='addr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer_table'),
        ),
        migrations.AlterField(
            model_name='sales_order',
            name='order_ID',
            field=models.CharField(blank=True, default='2263616', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sales_quote',
            name='quote_ID',
            field=models.CharField(blank=True, default='2847038', max_length=50, null=True),
        ),
    ]
