# Generated by Django 5.0.6 on 2025-01-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0037_alter_user_account_token_id_alter_warehouse_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_account',
            name='token_ID',
            field=models.CharField(default='ZlsrGG6aiR', max_length=12),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='code',
            field=models.CharField(default='8604243', max_length=255),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='token_id',
            field=models.CharField(default='KkUNiJdLNP', max_length=255),
        ),
    ]
