# Generated by Django 5.0.6 on 2024-12-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_pages_token_id_alter_user_token_id_state'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='State',
            new_name='states',
        ),
        migrations.AlterField(
            model_name='pages',
            name='token_id',
            field=models.CharField(default='AiCkhzA4JC', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='Token_ID',
            field=models.CharField(default='EUrLZ0nIPi', max_length=12),
        ),
    ]
