# Generated by Django 5.0.6 on 2024-12-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_state_states_alter_pages_token_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='states',
            old_name='Country',
            new_name='country',
        ),
        migrations.AlterField(
            model_name='pages',
            name='token_id',
            field=models.CharField(default='ztbxVikR5G', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='Token_ID',
            field=models.CharField(default='aNL3jE6MO6', max_length=12),
        ),
    ]
