# Generated by Django 5.0.6 on 2024-12-13 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stockin', '0001_initial'),
        ('main', '0012_alter_pages_token_id_alter_user_token_id_billing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='token_id',
            field=models.CharField(default='oIAyJif255', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='Token_ID',
            field=models.CharField(default='BUtqbBRDgP', max_length=12),
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('card_number', models.CharField(default='0', max_length=255)),
                ('month', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('code', models.CharField(default='0', max_length=255)),
                ('holders_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('plan', models.CharField(max_length=255)),
                ('subscription', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=65)),
                ('renew', models.CharField(max_length=255)),
                ('users', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=255)),
                ('payment_status', models.CharField(max_length=255)),
                ('auto_renew', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stockin.company_table')),
            ],
            options={
                'db_table': 'Billing',
            },
        ),
        migrations.CreateModel(
            name='SubHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=255)),
                ('subscription', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=65)),
                ('renew', models.CharField(max_length=255)),
                ('users', models.CharField(max_length=255)),
                ('payment_status', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=255)),
                ('auto_renew', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stockin.company_table')),
            ],
            options={
                'db_table': 'SubHistory',
            },
        ),
    ]
