# Generated by Django 5.0.6 on 2024-12-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_billing_reference_alter_pages_token_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='token_id',
            field=models.CharField(default='mym3C8RNsf', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='Token_ID',
            field=models.CharField(default='VfB5sm7yvJ', max_length=12),
        ),
    ]
