# Generated by Django 5.0.6 on 2024-12-17 10:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_pages_token_id_alter_user_token_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='renew',
        ),
        migrations.RemoveField(
            model_name='subhistory',
            name='renew',
        ),
        migrations.AddField(
            model_name='billing',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subhistory',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pages',
            name='token_id',
            field=models.CharField(default='pzz3sDLold', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='Token_ID',
            field=models.CharField(default='Q1gW4YF3hv', max_length=12),
        ),
    ]
