# Generated by Django 5.0.6 on 2025-01-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_pages_token_id_alter_user_token_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='address',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='code',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='country',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='holders_name',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='month',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='year',
        ),
        migrations.AlterField(
            model_name='pages',
            name='token_id',
            field=models.CharField(default='fGyOQiAUdG', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='Token_ID',
            field=models.CharField(default='9XS4auKLjA', max_length=12),
        ),
    ]
