# Generated by Django 5.0.6 on 2025-01-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_remove_billing_address_remove_billing_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='token_id',
            field=models.CharField(default='0nVSxlUHhl', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='Token_ID',
            field=models.CharField(default='yYahOtmVqA', max_length=12),
        ),
    ]
